#!/usr/bin/env python3
"""Regression tests: run Rust simulator with TOML configs and compare against reference data.

Two sets of tests:
  - Fortran reference: compare Rust output against Fortran golden data (legacy, to be removed)
  - Rust golden: compare Rust output against its own golden reference data

Usage:
    pytest tests/test_regression.py -v
    pytest tests/test_regression.py -k ref_orig -v
    pytest tests/test_regression.py -k rust_golden -v

Each test:
    1. Runs the Rust simulator with a TOML config (text output format)
    2. Compares photo.* and final.* against reference data
    3. Fails if any value deviates beyond tolerance
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
from aerocapture.io._fortran import parse_fortran_line

ROOT = Path(__file__).parent.parent
BINARY = ROOT / "src" / "rust" / "target" / "release" / "aerocapture"
REF_DIR = ROOT / "tests" / "reference_data"
GOLDEN_DIR = REF_DIR / "rust_golden"
OUTPUT_DIR = ROOT / "output"

# Test cases: (name, toml_config, reference_dir, files_to_compare)
# Skip fort.* (dead code in Rust), initial.* (not written by Rust),
# mission.* (not written by Rust), photo_temp.* (not written by Rust)
FORTRAN_REF_CASES = [
    (
        "ref_orig",
        "configs/test_ref_orig.toml",
        "ref_orig",
        ["photo.test_ref_orig", "final.test_ref_orig"],
    ),
    (
        "high_bank_orig",
        "configs/test_high_bank_orig.toml",
        "high_bank_orig",
        ["photo.test_high_bank_orig", "final.test_high_bank_orig"],
    ),
    (
        "guided_orig",
        "configs/test_guided_orig.toml",
        "guided_orig",
        ["photo.test_guided_orig", "final.test_guided_orig"],
    ),
]

# Rust golden reference cases: same configs, compared against Rust-generated golden outputs
RUST_GOLDEN_CASES = [
    (
        "rust_golden_ref",
        "configs/test_ref_orig.toml",
        "ref",
        ["photo.test_ref_orig", "final.test_ref_orig"],
    ),
    (
        "rust_golden_high_bank",
        "configs/test_high_bank_orig.toml",
        "high_bank",
        ["photo.test_high_bank_orig", "final.test_high_bank_orig"],
    ),
    (
        "rust_golden_guided",
        "configs/test_guided_orig.toml",
        "guided",
        ["photo.test_guided_orig", "final.test_guided_orig"],
    ),
]

# Tolerance: exact match (reference data generated by Rust TOML runs)
ATOL = 1e-10
RTOL = 1e-10


def parse_output_file(filepath: Path) -> list[list[float]]:
    """Parse a Fortran-format output file into rows of floats."""
    rows = []
    with open(filepath) as f:
        for line in f:
            values = parse_fortran_line(line)
            if values:
                rows.append(values)
    return rows


def compare_values(
    test_rows: list[list[float]],
    ref_rows: list[list[float]],
    skip_cols: set[int] | None = None,
    skip_first_row_cols: set[int] | None = None,
) -> tuple[bool, list[str]]:
    """Compare two sets of rows within tolerance."""
    errors = []
    if skip_cols is None:
        skip_cols = set()
    if skip_first_row_cols is None:
        skip_first_row_cols = set()

    if len(test_rows) != len(ref_rows):
        errors.append(f"Row count mismatch: test={len(test_rows)} ref={len(ref_rows)}")
        return False, errors

    max_abs = 0.0
    max_loc = ""

    for row_idx, (test_row, ref_row) in enumerate(zip(test_rows, ref_rows, strict=False)):
        if len(test_row) != len(ref_row):
            errors.append(f"Col count mismatch at row {row_idx}: test={len(test_row)} ref={len(ref_row)}")
            continue

        for col_idx, (tv, rv) in enumerate(zip(test_row, ref_row, strict=False)):
            if col_idx in skip_cols:
                continue
            if row_idx == 0 and col_idx in skip_first_row_cols:
                continue

            abs_dev = abs(tv - rv)
            rel_dev = abs_dev / max(abs(rv), 1e-300) if rv != 0.0 else abs_dev

            if abs_dev > ATOL and rel_dev > RTOL:
                errors.append(f"  row {row_idx}, col {col_idx}: test={tv:.10e} ref={rv:.10e} abs={abs_dev:.3e} rel={rel_dev:.3e}")

            if abs_dev > max_abs:
                max_abs = abs_dev
                max_loc = f"row {row_idx}, col {col_idx}"

    if max_abs > 0 and not errors:
        errors.append(f"Max deviation: {max_abs:.6e} at {max_loc} (within tolerance)")

    return len(errors) == 0 or all("within tolerance" in e for e in errors), errors


@pytest.fixture(scope="session", autouse=True)
def _build_rust() -> None:
    """Ensure Rust binary is built before running tests."""
    if not BINARY.exists():
        subprocess.run(["cargo", "build", "--release"], cwd=ROOT / "src" / "rust", check=True)


def _run_and_compare(toml_config: str, ref_base: Path, files: list[str]) -> None:
    """Run the simulator with a TOML config and compare output files against reference."""
    toml_path = ROOT / toml_config

    result = subprocess.run(
        [str(BINARY), str(toml_path)],
        capture_output=True,
        cwd=str(ROOT),
        timeout=60,
    )
    assert result.returncode == 0, f"Simulator failed:\n{result.stderr.decode()}"

    for filename in files:
        test_file = OUTPUT_DIR / filename
        ref_file = ref_base / filename

        assert test_file.exists(), f"Output file not found: {test_file}"
        assert ref_file.exists(), f"Reference file not found: {ref_file}"

        test_data = parse_output_file(test_file)
        ref_data = parse_output_file(ref_file)

        passed, errors = compare_values(test_data, ref_data)

        error_msg = f"\n{filename} comparison failed:\n" + "\n".join(errors[:20])
        if len(errors) > 20:
            error_msg += f"\n  ... and {len(errors) - 20} more"
        assert passed, error_msg


@pytest.mark.parametrize("name,toml_config,ref_subdir,files", FORTRAN_REF_CASES, ids=[t[0] for t in FORTRAN_REF_CASES])
def test_fortran_reference(name: str, toml_config: str, ref_subdir: str, files: list[str]) -> None:
    """Run simulator with TOML config and compare output against Fortran reference."""
    ref_base = REF_DIR / ref_subdir / "sorties"
    _run_and_compare(toml_config, ref_base, files)


@pytest.mark.parametrize("name,toml_config,ref_subdir,files", RUST_GOLDEN_CASES, ids=[t[0] for t in RUST_GOLDEN_CASES])
def test_rust_golden(name: str, toml_config: str, ref_subdir: str, files: list[str]) -> None:
    """Run simulator with TOML config and compare output against Rust golden reference."""
    ref_base = GOLDEN_DIR / ref_subdir
    _run_and_compare(toml_config, ref_base, files)
