rep_net = '/users/m024633/govit/Aerocapture/feedback_acc_short/exec/save_net/';
file_name_root = 'optim_net_Aerocap_';

close all;
Table_ind = sortrows([142;... 
107;...   
10;...    
114;...   
11;...    
12;...    
144;... 
14;...  
15;...  
16;...  
171;... 
172;... 
175;... 
176;... 
17;...  
182;... 
188;... 
189;... 
195;... 
197;... 
199;... 
19;...  
20;...  
213;... 
215;... 
220;... 
22;...  
23;...  
241;... 
242;... 
248;... 
24;...  
252;... 
256;... 
26;...  
27;...  
28;...  
2;...   
306;... 
310;... 
313;... 
314;... 
315;... 
33;...  
44;...  
4;...   
56;...  
60])'
Table_ind = sortrows([142;... 
107;...   
10;...    
114;...   
11;...    
12;...    
144;... 
14;...  
15;...  
16;...  
171;... 
17;...  
19;...  
20;...  
22;...  
23;...  
24;...  
26;...  
27;...  
28;...  
2;...   
33;...  
44;...  
4;...   
56;...  
60])'
%Table_ind = sortrows([2299])'
mov = avifile('essai_full.avi','fps',1)

for ii = 1:length(Table_ind)
    %ii = Table_ind(1);
    Table_ind(ii)
    eval(['load(''' rep_net file_name_root num2str(Table_ind(ii)) '.mat'')']);
    
    fid = fopen('../donnees/nn_param.temp','wt');
    nnet_out = PS.NS.nnet;
    fprintf(fid,'  \n');
    fprintf(fid,'   Caracteristiques neural network\n');
    fprintf(fid,'  \n');
    fprintf(fid,['           ' num2str(PS.NS.n1input) '   ninput\n']);
    fprintf(fid,['           ' num2str([PS.NS.n1hid1 PS.NS.n1hid2 PS.NS.n1hid3]) '   nhid\n']);
    fprintf(fid,['           ' num2str(PS.NS.n1output) '   noutput\n']);
    for i = 1:PS.NS.ncoef1
	    fprintf(fid,'%40.30f\n',nnet_out(i));
    end
    fclose(fid);
    
    !aerocap_nn < aerocap.in_msr_aller_nn_film > toto
    !aerocap_nn < aerocap.in_msr_aller_nn_film_mc > toto

    load('../sorties/photo.MC_1000_ftc_171108_new');
    photo_ftc = photo;
    load('../sorties/final.MC_1000_ftc_171108_new');
    load('../sorties/photo.ftc_nom_new');
    final_ftc = final;
    photo_ftc_nom = photo;
    load('../sorties/photo.nn_mc_film');
    photo_nn = photo;
    load('../sorties/final.nn_mc_film');
    load('../sorties/photo.nn_nom_film');
    photo_nn_nom = photo;
    load visu.ovr_res
    visu_ovr = visu;
    load visu.udr_res
    visu_udr = visu;

    indices_deb = (find(diff(photo_nn(:,1)) < 0)+1);
    indices_fin = [indices_deb-1;length(photo_nn(:,1))];
    indices_deb = [1;indices_deb];

    grey = 0.9;
    h = 10;

    scrsz = get(0,'ScreenSize');
    fig=figure('Position',[1 scrsz(4) scrsz(3) scrsz(4)]);
    subplot(2,2,1)
    plot(photo_nn_nom(:,19)/1000000,photo_nn_nom(:,20)/1000,'r','LineWidth',1.5)
    hold on;
    mm = 1;
    plot(photo_nn(indices_deb(mm):indices_fin(mm),19)/1000000,photo_nn(indices_deb(mm):indices_fin(mm),20)/1000,'b-');
    fill([visu_ovr(1,1);visu_ovr(:,1);visu_ovr(end,1)],[0;visu_ovr(:,2);0],[grey grey grey],'EdgeColor','k');
    fill([5;5;visu_udr(1,1);visu_udr(:,1);visu_udr(end,1);-7;-7],[2.2;0;0;visu_udr(:,2);0;0;2.2],[grey grey grey],'EdgeColor','k');
    for mm = 1:size(indices_deb,1)-1
        plot(photo_nn(indices_deb(mm):indices_fin(mm),19)/1000000,photo_nn(indices_deb(mm):indices_fin(mm),20)/1000,'b-');
    end
    plot(photo_nn_nom(:,19)/1000000,photo_nn_nom(:,20)/1000,'r','LineWidth',1.5)
    xlabel('Orbital energy (MJ/kg)')
    ylabel('Dynamic pressure (kPa)')
    legend('Nominal','Monte Carlo','Location','NorthWest')
    set(gca,'Layer','top');
    box off;
    grid on;
    box on;
    axis tight;
    subplot(2,2,2)
    plot(photo_nn_nom(:,19)/1000000,photo_nn_nom(:,10),'r','LineWidth',1.5)
    hold on;
    for mm = 1:size(indices_deb,1)-1
        plot(photo_nn(indices_deb(mm):indices_fin(mm),19)/1000000,photo_nn(indices_deb(mm):indices_fin(mm),10),'b-');
    end
    plot(photo_nn_nom(:,19)/1000000,photo_nn_nom(:,10),'r','LineWidth',1.5)
    xlabel('Orbital energy (MJ/kg)')
    ylabel('Inclination (deg)')
    legend('Nominal','Monte Carlo','Location','NorthEast')
    box off;
    grid on;
    box on;
    axis tight;
    subplot(2,2,3)
    plot(photo_nn_nom(:,19)/1000000,photo_nn_nom(:,15),'r','LineWidth',1.5)
    hold on;
    for mm = 1:size(indices_deb,1)-1
        plot(photo_nn(indices_deb(mm):indices_fin(mm),19)/1000000,photo_nn(indices_deb(mm):indices_fin(mm),15),'b-');
    end
    plot(photo_nn_nom(:,19)/1000000,photo_nn_nom(:,15),'r','LineWidth',1.5)
    xlabel('Orbital energy (MJ/kg)')
    ylabel('Bank angle (deg)')
    legend('Nominal','Monte Carlo','Location','SouthEast')
    box off;
    grid on;
    box on;
    axis tight;
    subplot(2,2,4)
    [y,x] = hist(final(:,43),h);
    bar(x,y/length(final(:,43)));
    hi = findobj(gca,'Type','patch');
    set(hi,'FaceColor','r','EdgeColor','k')
    hold on;
    [x,y] = cdfgov(final(:,43)');
    plot(x,y);
    xlabel('Correction cost (m/s)');
    ylabel('Distribution (-)');
    axis tight;
    axis([100 1500 0 1]);
    set(gca,'Xscale','log','XTickLabel',{'100';'1000'})
    box off;
    grid on;
    box on;
    set(gcf,'PaperType','USLetter');
    taille=get(gcf,'PaperSize');
    set(gcf,'PaperSize',[taille(2) taille(1)]);
    orient tall;
    F = getframe(fig);
    mov = addframe(mov,F);
    close all;
end
mov = close(mov);
