base = ["../training/common.toml", "../missions/mars.toml"]

[guidance]
type = "piecewise_constant"

[guidance.piecewise_constant]
energy_min = -10.0
energy_max = 10.0
n_segments = 200

[data]
results_suffix = ".piecewise_constant"
