# MSR outbound — FTC GA training, 10 MC sims per evaluation
base = ["../missions/mars.toml", "common.toml"]

[guidance]
type = "ftc"
reference_bank_angle = 64.77026

[data]
results_suffix = ".train_ftc"
