# MSR outbound — NN training, 50 MC sims per evaluation, domain-based dispersions
base = ["../missions/mars.toml", "common.toml"]

[guidance]
type = "neural_network"

[navigation]
density_filter_gain = 0.9753403215253369
density_gain_max_delta = 0.49926943071269225

[network]
layer_sizes = [16, 32, 8, 4, 2]
activations = ["mish", "mish", "mish", "linear"]
input_mask = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
# input_mask = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
# input_mask = [18, 12, 15, 0, 6, 14, 13, 11, 4, 3, 5]
output_interpretation = "atan2"

[[network.architecture]]
type = "dense"
input_size = 23
output_size = 32
activation = "swish"

[[network.architecture]]
type = "dense"
input_size = 32
output_size = 16
activation = "swish"

[[network.architecture]]
type = "dense"
input_size = 16
output_size = 2
activation = "asinh"

[data]
neural_network = "data/neural_network/nn_model.json"
results_suffix = ".train_nn"

[guidance.ftc]
capture_damping = 0.7
capture_frequency = 0.072
capture_pdyn_margin = 1.75
altitude_damping = 0.7
altitude_frequency = 0.08
exit_velocity_threshold = 4400.0
exit_pdyn_margin = 1.75
exit_altitude_threshold = 60.0
exit_radial_vel_gain = 10.0
exit_apoapsis_threshold = 100.0
security_capture = 1
security_exit = 3
longi_activation = 1000.0
longi_inhibition = -1000.0
pdyn_min = 0.0
pressure_coeff_base = -134.4
pressure_coeff_scale_height = 6.9
gain_fade_start_km = 80.0
gain_fade_end_km = 100.0
