# MSR outbound — NN training, 50 MC sims per evaluation, domain-based dispersions
base = ["../missions/mars.toml", "common.toml"]

[guidance]
type = "neural_network"

[navigation]
density_filter_gain = 0.6914060018624361
density_gain_max_delta = 0.10161760731237457

[network]
layer_sizes = [16, 32, 8, 2]
activations = ["tanh", "tanh", "asinh"]

[data]
neural_network = "data/neural_network/nn_model.json"
results_suffix = ".train_nn"
