# MSR outbound — FNPAG GA training, 10 MC sims per evaluation
base = ["../missions/mars.toml", "common.toml"]

[guidance]
type = "fnpag"
reference_bank_angle = 64.77026

[data]
results_suffix = ".train_fnpag"
