"""Standalone NN input behavior report. See
docs/superpowers/specs/2026-05-29-nn-input-report-design.md."""

from __future__ import annotations

import argparse
import json
import tempfile
from pathlib import Path

import numpy as np
import numpy.typing as npt

from aerocapture.training.ablation import NN_INPUT_NAMES, _load_cost_kwargs
from aerocapture.training.charts_nn_inputs import chart_nn_input_panel
from aerocapture.training.evaluate import NN_INPUT_REPORT_SEED_OFFSET, make_reserved_seeds
from aerocapture.training.toml_utils import load_toml_with_bases
from aerocapture.training.typst_utils import check_typst, compile_typst

# class codes
BLUE_LOW_DV = 0
RED_HIGH_DV = 1


def classify_by_dv(dv: npt.NDArray[np.float64], threshold: float) -> npt.NDArray[np.int8]:
    """Blue (0) if final DV < threshold, red (1) otherwise."""
    return np.where(np.asarray(dv) < threshold, BLUE_LOW_DV, RED_HIGH_DV).astype(np.int8)


def input_summary(
    X_list: list[npt.NDArray[np.float64]],
    traj_class: npt.NDArray[np.int8],
    names: list[str],
    in_mask: set[int],
) -> list[dict[str, object]]:
    """Per-input stats over all (trajectory x timestep) samples.

    Returns one dict per input with index, name, p1/p50/p99, frac_out_of_range
    (fraction of samples with |value| > 1), separation
    (|mean_red - mean_blue| / pooled_std), and in_mask. Sorted by
    frac_out_of_range desc, then separation desc.
    """
    n_inputs = len(names)
    blue_parts = [X_list[i] for i in range(len(X_list)) if traj_class[i] == BLUE_LOW_DV]
    red_parts = [X_list[i] for i in range(len(X_list)) if traj_class[i] == RED_HIGH_DV]
    blue = np.concatenate(blue_parts, axis=0) if blue_parts else np.empty((0, n_inputs))
    red = np.concatenate(red_parts, axis=0) if red_parts else np.empty((0, n_inputs))
    alls = np.concatenate(list(X_list), axis=0)
    rows: list[dict[str, object]] = []
    for j in range(n_inputs):
        col = alls[:, j]
        p1, p50, p99 = (float(v) for v in np.percentile(col, [1, 50, 99]))
        frac_oor = float(np.mean(np.abs(col) > 1.0))
        if blue.shape[0] and red.shape[0]:
            mb, mr = float(blue[:, j].mean()), float(red[:, j].mean())
            pooled = float(np.sqrt(0.5 * (blue[:, j].var() + red[:, j].var()))) + 1e-12
            sep = abs(mr - mb) / pooled
        else:
            sep = 0.0
        rows.append(
            {
                "index": j,
                "name": names[j],
                "p1": p1,
                "p50": p50,
                "p99": p99,
                "frac_out_of_range": frac_oor,
                "separation": sep,
                "in_mask": j in in_mask,
            }
        )
    rows.sort(key=lambda r: (r["frac_out_of_range"], r["separation"]), reverse=True)
    return rows


def _resolve_mask(toml_path: str, model_path: str | None = None) -> set[int]:
    """Resolve the deployed model's input_mask (which the Rust runtime actually
    uses) for panel "(unused)" greying. Prefers the JSON model's embedded mask
    over the TOML config -- the two can differ when --toml is not the training
    config. Falls back to the TOML mask, then the [0..16) backward-compat default."""
    cfg = load_toml_with_bases(Path(toml_path))
    nn_path = model_path or cfg.get("data", {}).get("neural_network")
    if nn_path:
        try:
            model_mask = json.loads(Path(nn_path).read_text()).get("input_mask")
            if model_mask is not None:
                return set(model_mask)
        except (OSError, json.JSONDecodeError):  # fmt: skip  # ruff fmt strips the parens -> invalid syntax
            pass
    mask = cfg.get("network", {}).get("input_mask")
    return set(mask) if mask is not None else set(range(16))


def _default_dv_threshold(toml_path: str) -> float:
    return float(_load_cost_kwargs(toml_path).get("dv_threshold", 1000.0))


_TYPST_TEMPLATE = r"""// Auto-generated by aerocapture.training.nn_input_report.
// Lives in the report dir alongside summary.json + the SVG panels, so all
// image paths are bare filenames Typst resolves relative to this file.
#let meta = json("summary.json")

#set page(paper: "a4", margin: (top: 1.6cm, bottom: 1.4cm, left: 1.3cm, right: 1.3cm))
#set text(size: 9pt)

#align(center)[
  #text(size: 20pt, weight: "bold")[NN Input Behavior Report]
  #v(0.15cm)
  #text(size: 13pt)[#meta.scheme]
  #v(0.1cm)
  #text(size: 9pt, fill: luma(110))[
    DV threshold #meta.dv_threshold m/s · blue (low DV) #meta.n_blue / red (high DV) #meta.n_red · #meta.n_sims sims
  ]
]
#v(0.3cm)

== Per-input summary (sorted by saturation)

#text(size: 8pt, fill: luma(110))[
  %|v|>1 = fraction of samples outside the network's expected [-1, 1] range.
  sep = |mean(red) - mean(blue)| / pooled-sigma (how strongly the input separates costly from cheap runs).
]
#v(0.15cm)

#table(
  columns: (auto, auto, auto, auto, auto, auto, auto),
  stroke: none,
  inset: (x: 5pt, y: 2.5pt),
  align: (left, center, right, right, right, right, right),
  table.hline(stroke: 1.0pt),
  [*input*], [*in mask*], [*%|v|>1*], [*sep*], [*p1*], [*p50*], [*p99*],
  table.hline(stroke: 0.4pt),
  ..meta.inputs.map(r => (
    [#r.name],
    if r.in_mask [yes] else [#text(fill: luma(150))[--]],
    [#calc.round(r.frac_out_of_range * 100, digits: 1)%],
    [#calc.round(r.separation, digits: 2)],
    [#calc.round(r.p1, digits: 2)],
    [#calc.round(r.p50, digits: 2)],
    [#calc.round(r.p99, digits: 2)],
  )).flatten(),
  table.hline(stroke: 1.0pt),
)

#pagebreak()

== Input panels (time | energy estimated), most-saturated first

#for r in meta.inputs [
  #text(weight: "bold")[\[#r.index\] #r.name]
  #h(1fr)
  #text(size: 8pt, fill: luma(110))[
    sat #calc.round(r.frac_out_of_range * 100, digits: 0)% · sep #calc.round(r.separation, digits: 2)#if not r.in_mask [ · (unused)]
  ]
  #grid(columns: (1fr, 1fr), gutter: 5pt,
    image(r.time_svg, width: 100%),
    image(r.energy_svg, width: 100%),
  )
  #v(0.15cm)
]
"""


def _compile_pdf(out_dir: Path) -> Path | None:
    """Compile the rendered SVGs + summary.json into nn_input_report.pdf via the
    Typst CLI. Returns the PDF path, or None (with a message) if Typst is absent
    or the compile fails -- the SVGs + JSON remain usable either way."""
    if not check_typst():
        print(f"  [nn_input_report] Typst not installed; SVGs + summary.json at {out_dir} (no PDF). Install with `brew install typst`.")
        return None
    pdf_path = out_dir / "nn_input_report.pdf"
    with tempfile.NamedTemporaryFile("w", suffix=".typ", delete=False, dir=out_dir) as tmpl_file:
        tmpl_file.write(_TYPST_TEMPLATE)
        tmpl_path = Path(tmpl_file.name)
    try:
        if not compile_typst(tmpl_path, pdf_path, label="nn_input_report"):
            return None
    finally:
        tmpl_path.unlink(missing_ok=True)
    return pdf_path


def run_report(
    toml_path: str,
    n_sims: int = 500,
    output_dir: Path | None = None,
    dv_threshold: float | None = None,
    overrides: dict[str, object] | None = None,
) -> Path:
    """Run the deployed NN over n_sims seeds, classify by final DV, render
    per-input panels (time + energy) + a summary table."""
    out_dir = Path(output_dir) if output_dir else Path("nn_input_report")
    out_dir.mkdir(parents=True, exist_ok=True)
    thr = dv_threshold if dv_threshold is not None else _default_dv_threshold(toml_path)
    # Honor an overridden model path so panel greying reflects the model actually run.
    override_model = overrides.get("data.neural_network") if overrides else None
    in_mask = _resolve_mask(toml_path, str(override_model) if override_model is not None else None)

    seeds = make_reserved_seeds(0, NN_INPUT_REPORT_SEED_OFFSET, n_sims)
    import aerocapture_rs

    recs = aerocapture_rs.collect_nn_inputs(toml_path, seeds, overrides=overrides)

    X_list = [r["X"] for r in recs]
    time_list = [r["time"] for r in recs]
    energy_list = [r["energy"] for r in recs]
    dv = np.array([float(r["dv"]) for r in recs], dtype=np.float64)
    klass = classify_by_dv(dv, thr)

    rows = input_summary(X_list, klass, NN_INPUT_NAMES, in_mask)
    # Attach the per-input SVG basenames so the Typst template (which lives in
    # out_dir and resolves paths relative to itself) can embed them directly.
    for r in rows:
        j, nm = r["index"], r["name"]
        r["time_svg"] = f"nn_input_{j:02d}_{nm}_time.svg"
        r["energy_svg"] = f"nn_input_{j:02d}_{nm}_energy.svg"
    summary = {
        "scheme": Path(toml_path).stem,
        "dv_threshold": thr,
        "n_sims": n_sims,
        "n_blue": int(np.sum(klass == BLUE_LOW_DV)),
        "n_red": int(np.sum(klass == RED_HIGH_DV)),
        "inputs": rows,
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2))

    for j, nm in enumerate(NN_INPUT_NAMES):
        chart_nn_input_panel(
            X_list,
            time_list,
            klass,
            j,
            nm,
            j in in_mask,
            out_dir / f"nn_input_{j:02d}_{nm}_time.svg",
            x_label="time (s)",
        )
        chart_nn_input_panel(
            X_list,
            energy_list,
            klass,
            j,
            nm,
            j in in_mask,
            out_dir / f"nn_input_{j:02d}_{nm}_energy.svg",
            x_label="energy estimated (MJ/kg)",
        )

    _compile_pdf(out_dir)
    return out_dir


def main() -> None:
    ap = argparse.ArgumentParser(description="NN input behavior report")
    ap.add_argument("training_dir")
    ap.add_argument("--toml", required=True)
    ap.add_argument("--n-sims", type=int, default=500)
    ap.add_argument("--dv-threshold", type=float, default=None)
    ap.add_argument("--output-dir", default=None)
    args = ap.parse_args()
    out = args.output_dir or str(Path(args.training_dir) / "nn_input_report")
    run_report(args.toml, n_sims=args.n_sims, output_dir=Path(out), dv_threshold=args.dv_threshold)
    print(f"NN input report written to {out}")


if __name__ == "__main__":
    main()
